-- Create chat_logs table for storing AI chat interactions
CREATE TABLE IF NOT EXISTS chat_logs (
    id SERIAL PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    user_sub VARCHAR(255) NOT NULL,
    conversation_id VARCHAR(255), -- Group related messages
    message TEXT NOT NULL,
    response TEXT NOT NULL,
    
    -- Training & Analytics Fields
    user_feedback INTEGER CHECK (user_feedback IN (-1, 0, 1)), -- -1: negative, 0: neutral, 1: positive
    response_helpful BOOLEAN,
    conversation_resolved BOOLEAN,
    category VARCHAR(100), -- e.g., 'billing', 'claims', 'eligibility', 'technical'
    intent VARCHAR(100), -- detected user intent
    confidence_score DECIMAL(3,2), -- model confidence 0.00-1.00
    response_time_ms INTEGER,
    
    -- Metadata
    prompt_tokens INTEGER DEFAULT 0,
    completion_tokens INTEGER DEFAULT 0,
    total_tokens INTEGER DEFAULT 0,
    model_version VARCHAR(100),
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraints
    CONSTRAINT fk_chat_logs_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

-- Simplified conversation ratings table
CREATE TABLE IF NOT EXISTS conversation_ratings (
    id SERIAL PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    user_sub VARCHAR(255) NOT NULL,
    conversation_id VARCHAR(255) NOT NULL,
    
    -- Simple rating fields
    overall_rating INTEGER NOT NULL CHECK (overall_rating >= 1 AND overall_rating <= 5),
    feedback_text TEXT,
    
    -- Conversation metadata
    conversation_length INTEGER DEFAULT 0,
    conversation_duration_seconds INTEGER DEFAULT 0,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    UNIQUE(tenant_id, user_sub, conversation_id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_chat_logs_tenant_user ON chat_logs(tenant_id, user_sub);
CREATE INDEX IF NOT EXISTS idx_chat_logs_created_at ON chat_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_chat_logs_tenant_created ON chat_logs(tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_chat_logs_conversation ON chat_logs(conversation_id);
CREATE INDEX IF NOT EXISTS idx_chat_logs_category ON chat_logs(category);
CREATE INDEX IF NOT EXISTS idx_chat_logs_feedback ON chat_logs(user_feedback);

CREATE INDEX IF NOT EXISTS idx_conversation_ratings_tenant ON conversation_ratings(tenant_id);
CREATE INDEX IF NOT EXISTS idx_conversation_ratings_user ON conversation_ratings(user_sub);
CREATE INDEX IF NOT EXISTS idx_conversation_ratings_created ON conversation_ratings(created_at);
CREATE INDEX IF NOT EXISTS idx_conversation_ratings_rating ON conversation_ratings(overall_rating);

-- Add comments for documentation
COMMENT ON TABLE chat_logs IS 'Stores AI chatbot interactions for analytics and history';
COMMENT ON COLUMN chat_logs.tenant_id IS 'Reference to the tenant where the chat occurred';
COMMENT ON COLUMN chat_logs.user_sub IS 'Cognito user sub (UUID) of the user who sent the message';
COMMENT ON COLUMN chat_logs.message IS 'The user message sent to the AI';
COMMENT ON COLUMN chat_logs.response IS 'The AI response generated by Bedrock';
COMMENT ON COLUMN chat_logs.created_at IS 'Timestamp when the chat interaction occurred';

-- Table for storing common questions and approved responses
CREATE TABLE IF NOT EXISTS knowledge_base (
    id SERIAL PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    question_pattern TEXT NOT NULL,
    approved_response TEXT NOT NULL,
    category VARCHAR(100),
    usage_count INTEGER DEFAULT 0,
    effectiveness_score DECIMAL(3,2) DEFAULT 0.00,
    created_by VARCHAR(255),
    approved_by VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

-- Table for tracking conversation patterns
CREATE TABLE IF NOT EXISTS conversation_analytics (
    id SERIAL PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    category VARCHAR(100),
    total_conversations INTEGER DEFAULT 0,
    resolved_conversations INTEGER DEFAULT 0,
    avg_satisfaction_score DECIMAL(3,2),
    common_questions JSONB,
    escalation_triggers JSONB,
    
    UNIQUE(tenant_id, date, category),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

-- Indexes for analytics queries
CREATE INDEX IF NOT EXISTS idx_chat_logs_tenant_category ON chat_logs(tenant_id, category);
CREATE INDEX IF NOT EXISTS idx_chat_logs_feedback ON chat_logs(user_feedback, response_helpful);
CREATE INDEX IF NOT EXISTS idx_chat_logs_conversation ON chat_logs(conversation_id); 