// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apkilubmiqfvnutqccbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwa2lsdWJtaXFmdm51dHFjY2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzY1ODMsImV4cCI6MjA1Mzg1MjU4M30.gIgiIaIRgL43zuTQJXfgAwAsTGPXgJHMxQeLDKWemNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);